# Generated by Django 5.0.1 on 2024-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.FileField(default='path/to/default/image.jpg', upload_to='../media/images'),
        ),
    ]
