# Generated by Django 5.0.1 on 2024-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img', models.FileField(default='path/to/default/image.jpg', upload_to='static/media/images/')),
                ('category', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(default='path/to/default/image.jpg', upload_to='static/media/images/'),
        ),
    ]
